export const bachelorettes = {
  muffy: {
    heartLevels: {
      1: 1,
      2: 8,
      3: 12,
      4: 16.5,
    },
    gifts: {
      flower: 1,
      halfFlower: 0.5,
      milk: 0.5,
      talking: 1,
      secondTalk: 0.25,
      mineItem: 1,
      record: 1,
      heartEvent: 1,
    },
  },
  celia: {
    heartLevels: {
      1: 3,
      2: 8,
      3: 13,
      4: 18,
    },
    gifts: {
      flower: 1,
      egg: 1,
      heartEvent: 1,
    },
  },
  nami: {
    heartLevels: {
      1: 10,
      2: 20,
      3: 30,
      4: 40,
    },
    gifts: {
      meal: 0.5,
      trickBlue: 1,
      record: 0.5,
      mineItem: 0.25,
      talking: 1,
      heartEvent: 2.5,
    },
  },
};

export const village = {
  carter: {
    friend: 11,
    likes: ['fish'],
    color: '#0000bd',
    time: '10am',
  },
  chris: {
    friend: 9,
    likes: ['flower'],
    color: '#5d0016',
    time: '6-9am',
  },
  cody: {
    friend: 13,
    likes: ['flower'],
    color: '#f20019',
    time: '6pm',
  },
  daryl: {
    friend: 8,
    likes: ['fish', 'coin'],
    color: '#827800',
    time: '5:30pm',
  },
  hardy: {
    friend: 12,
    likes: ['fish', 'flower'],
    color: '#8f00c7',
    time: '10am',
  },
  galen: {
    friend: 8,
    likes: ['mugwort'],
    color: '#0086fe',
    time: '4pm',
  },
  griffin: {
    friend: 12,
    likes: ['trick blue'],
    color: '#008000',
    time: '2pm',
  },
  kate: {
    friend: 12,
    likes: ['flower'],
    color: '#00fefe',
    time: '6am',
  },
  mukumuku: {
    friend: 8,
    likes: ['flower', 'fish'],
    color: '#fffff0',
    time: 'winter',
  },
  rock: {
    friend: 20,
    likes: ['joy flower'],
    color: '#262626',
    time: '12pm',
  },
  romana: {
    friend: 12,
    likes: ['flower'],
    color: '#70fe00',
    time: '3-5pm',
  },
  sebastian: {
    friend: 12,
    likes: ['fish'],
    color: '#fefe00',
    time: '9am',
  },
  tim: {
    friend: 5,
    likes: ['milk'],
    color: '#fed38b',
    time: '6-7pm',
  },
  vesta: {
    friend: 7,
    likes: ['flower'],
    color: '#a0d681',
    time: '10:30am',
  },
  wally: {
    friend: 9,
    likes: ['milk'],
    color: '#fe8420',
    time: '8-9am',
  },
  takakura: {
    friend: 5,
    likes: ['light pickle'],
    color: '#fe68fe',
    time: '7-10pm',
  },
};

export const trophies = [
  { id: 1, name: 'Plenty of Plants' },
  { id: 2, name: 'Chug, Chug, Chug!' },
  { id: 3, name: 'Game Time' },
  { id: 4, name: 'Hook, Line and Sinker' },
  { id: 5, name: 'Moo Born' },
  { id: 6, name: 'Fresh Milk' },
  { id: 7, name: 'Happy Heifer' },
  { id: 8, name: 'Quack, Quack!' },
  { id: 9, name: 'Golden Groomer' },
  { id: 10, name: 'Hatched' },
  { id: 11, name: 'Sure Beats Walking!' },
  { id: 12, name: 'Main Course' },
  { id: 13, name: 'Third Generation' },
  { id: 14, name: 'Construction Worker' },
  { id: 15, name: 'Dog Lover' },
  { id: 16, name: 'The Right Tool for the Job' },
  { id: 17, name: 'Record Keeping' },
  { id: 18, name: 'Tidy Tombstone' },
  { id: 19, name: 'Diligent Digger', subtask: ['TabletC', 'TabletD', 'TabletE', 'TabletF', 'TabletG',] },
  { id: 20, name: 'Serious Celebrator', subtask: ['Spring', 'Summer', 'Fall', 'Winter'] },
  { id: 21, name: 'A Hard Bargain' },
  { id: 22, name: 'Veterinarian' },
  { id: 23, name: 'Lights in the Sky', subtask: ['CS1', 'CS2', 'CS3', 'CS4', 'CS5', 'CS6'] },
  { id: 24, name: 'Rise and Shine' },
  { id: 25, name: 'Chapter 1' },
  { id: 26, name: 'Chapter 2' },
  { id: 27, name: 'Chapter 3' },
  { id: 28, name: 'Chapter 4' },
  { id: 29, name: 'Chapter 5' },
  { id: 30, name: 'Chapter 6' },
];

export default bachelorettes;
